#!/usr/bin/env bash
#options
shopt -s nullglob #if the glob doesn't match any files it should not return the glob

which tsc >> /dev/null
if [ $? != 0 ]; then
    echo "The typescript compiler is not installed. Doing nothing."
    exit
fi

#sourcing environment variables
if [ -e ./.env ]; then
	source ./.env
else
	echo "You do not have a .env file set up for this environment. Aborting."
	exit 1
fi

if [ -z ${DEV_WEBROOT} ]; then
	echo "DEV_WEBROOT is not set. Aborting."
	exit 1
fi

if [ ! -d ${DEV_WEBROOT} ]; then
	echo "DEV_WEBROOT is not a valid dir. Aborting."
	exit 1
fi

#clean webroot
cleanup_list=${DEV_WEBROOT}/*
if [ -n ${cleanup_list:+"notempty"} ]; then
	#rm -r $cleanup_list #deleting of old stuff temporarily disabled
	test #nop because bash doesn't like empty if blocks
fi

#individual files
cp ./*.html ${DEV_WEBROOT}
cp ./*.css ${DEV_WEBROOT}

#folders
cp -r ./assets/ ${DEV_WEBROOT}

tsc --outDir ${DEV_WEBROOT}
